version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=etablissement
      - MYSQL_ROOT_PASSWORD=admin
  springboot-docker-cotnainer:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/etablissement
    depends_on:
      - mysql-standalone  
